import {
  Basics,
  SignIn,
  Password,
  Mfa,
  Attributes,
  Recovery,
  Messaging,
  Devices,
  Security,
} from './UserPoolSteps.jsx'
import { AppClients } from './AppClients.jsx'
import { Domain } from './Domain.jsx'
import { Review } from './Review.jsx'

export const STEPS = [
  {
    group: 'User Pool',
    id: 'basics',
    label: 'Pool basics',
    eyebrow: 'User Pool',
    title: 'Pool basics',
    desc: 'Name the pool, choose a region, and set protection and tagging.',
    Component: Basics,
  },
  {
    group: 'User Pool',
    id: 'signin',
    label: 'Sign-in experience',
    eyebrow: 'User Pool',
    title: 'Sign-in experience',
    desc: 'Choose how users identify themselves and which attributes are verified.',
    Component: SignIn,
  },
  {
    group: 'User Pool',
    id: 'password',
    label: 'Password policy',
    eyebrow: 'User Pool',
    title: 'Password policy',
    desc: 'Define the password complexity rules enforced for all users.',
    Component: Password,
  },
  {
    group: 'User Pool',
    id: 'mfa',
    label: 'Multi-factor auth',
    eyebrow: 'User Pool',
    title: 'Multi-factor authentication',
    desc: 'Require or offer a second authentication factor.',
    Component: Mfa,
  },
  {
    group: 'User Pool',
    id: 'attributes',
    label: 'Attributes',
    eyebrow: 'User Pool',
    title: 'User attributes',
    desc: 'Required standard attributes and any custom attributes to store.',
    Component: Attributes,
  },
  {
    group: 'User Pool',
    id: 'recovery',
    label: 'Account recovery',
    eyebrow: 'User Pool',
    title: 'Account recovery',
    desc: 'How users recover access to their accounts.',
    Component: Recovery,
  },
  {
    group: 'User Pool',
    id: 'messaging',
    label: 'Email & SMS',
    eyebrow: 'User Pool',
    title: 'Messaging',
    desc: 'Email/SMS delivery providers and message templates.',
    Component: Messaging,
  },
  {
    group: 'User Pool',
    id: 'devices',
    label: 'Device tracking',
    eyebrow: 'User Pool',
    title: 'Device tracking',
    desc: 'Remember user devices for adaptive authentication.',
    Component: Devices,
  },
  {
    group: 'User Pool',
    id: 'security',
    label: 'Security & triggers',
    eyebrow: 'User Pool',
    title: 'Advanced security & Lambda triggers',
    desc: 'Threat protection mode and Lambda customizations.',
    Component: Security,
  },
  {
    group: 'App Clients',
    id: 'clients',
    label: 'App clients',
    eyebrow: 'Isolation',
    title: 'App clients',
    desc: 'Per-application access boundaries into the user pool.',
    Component: AppClients,
  },
  {
    group: 'Domain',
    id: 'domain',
    label: 'Hosted UI domain',
    eyebrow: 'Domain',
    title: 'Hosted UI domain',
    desc: 'Optional managed login domain and OAuth endpoints.',
    Component: Domain,
  },
  {
    group: 'Generate',
    id: 'review',
    label: 'Review & generate',
    eyebrow: 'Generate',
    title: 'Review & generate template',
    desc: 'Validate the configuration and export the CloudFormation template.',
    Component: Review,
  },
]
