/**
 * Auth configuration — generated by `npx auth-client init`.
 *
 * This file belongs to YOUR project. The base URL comes from the environment
 * so the same build can point at local, staging and production.
 */
import { createAuthClient } from '@7edge/auth-client'

/**
 * Vite exposes env vars prefixed with VITE_ on `import.meta.env`.
 *  - Create React App:  process.env.REACT_APP_API_BASE_URL
 *  - Next.js:           process.env.NEXT_PUBLIC_API_BASE_URL
 */
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL

if (!API_BASE_URL) {
  throw new Error(
    'VITE_API_BASE_URL is not set. Add it to .env and restart the dev server — ' +
    'Vite only reads .env at startup.'
  )
}

export const authConfig = {
  baseURL: API_BASE_URL,

  // Renew the token this many seconds before it expires.
  expirySkewSeconds: 30,

  // Keep every open tab in sync on refresh and logout.
  crossTab: true,

  // Fired when a refresh fails and the session cannot be recovered.
  onForceLogout: () => {
    // e.g. redirect to your login route:
    // window.location.href = '/login'
  },
}

/**
 * A single client for the whole app. Import this anywhere — including
 * non-React code such as an API layer that needs `getValidToken()`.
 */
export const authClient = createAuthClient(authConfig)
