/**
 * Auth barrel — generated by `npx auth-client init`.
 *
 * Import auth from one place in your app:
 *   import { AuthProvider, useAuth, AuthFlow } from './auth'
 */
export { authClient, authConfig, API_BASE_URL } from './config'

// Your editable screens. Change these, don't fork the library.
export { default as AuthFlow } from './AuthFlow'
export { default as SignIn } from './screens/SignIn'
export { default as SignUp } from './screens/SignUp'
export { default as OtpVerify } from './screens/OtpVerify'
export { default as ForgotPassword } from './screens/ForgotPassword'
export { default as ResetPassword } from './screens/ResetPassword'
export { default as ChangePassword } from './screens/ChangePassword'
export { default as DeleteAccount } from './screens/DeleteAccount'

// Re-exported from the library so you never import from two places.
export { AuthProvider, useAuth, decodeJWT } from '@7edge/auth-client'
