import { AppClient, AuthConfig, CustomAttribute, LambdaTriggers } from '../types';

const LAMBDA_TRIGGER_CFN_KEYS: Record<keyof LambdaTriggers, string> = {
  preSignUp: 'PreSignUp',
  postConfirmation: 'PostConfirmation',
  preAuthentication: 'PreAuthentication',
  postAuthentication: 'PostAuthentication',
  customMessage: 'CustomMessage',
  preTokenGeneration: 'PreTokenGeneration',
  userMigration: 'UserMigration',
  defineChallenge: 'DefineAuthChallenge',
  createChallenge: 'CreateAuthChallenge',
  verifyChallenge: 'VerifyAuthChallengeResponse',
};

/**
 * Generates a CloudFormation YAML template string from an AuthConfig.
 * Ported from cognito-panel's cfnGenerator.js so the CLI and the panel
 * produce identical templates from the same wizard answers.
 */
export function generateCfnTemplate(config: AuthConfig): string {
  const {
    provider,
    region,
    poolName,
    signInOptions,
    passwordPolicy,
    mfa,
    appClients,
    lambdaTriggers,
    selfSignup,
    emailVerification,
    deletionProtection,
    customAttributes,
  } = config;

  const aliasAttrs: string[] = [];
  if (signInOptions.includes('email')) aliasAttrs.push('email');
  if (signInOptions.includes('phone')) aliasAttrs.push('phone_number');

  const autoVerifiedAttrs: string[] = [];
  if (emailVerification) autoVerifiedAttrs.push('email');
  if (signInOptions.includes('phone')) autoVerifiedAttrs.push('phone_number');

  const recoveryMechanisms = autoVerifiedAttrs.length
    ? autoVerifiedAttrs.map((attr, i) => ({
        name: attr === 'email' ? 'verified_email' : 'verified_phone_number',
        priority: i + 1,
      }))
    : [{ name: 'admin_only', priority: 1 }];

  const mfaConfig = mfa.enabled ? (mfa.mode === 'required' ? 'ON' : 'OPTIONAL') : 'OFF';

  const smsConfig =
    mfa.enabled && mfa.methods.includes('sms')
      ? `
      SmsConfiguration:
        ExternalId: !Sub '\${AWS::StackName}-sms-external-id'
        SnsCallerArn: !GetAtt CognitoSMSRole.Arn`
      : '';

  const enabledMfas = mfa.enabled
    ? `\n      EnabledMfas:${mfa.methods.includes('totp') ? '\n        - SOFTWARE_TOKEN_MFA' : ''}${
        mfa.methods.includes('sms') ? '\n        - SMS_MFA' : ''
      }`
    : '';

  const lambdaConfig = buildLambdaConfig(lambdaTriggers);

  const appClientResources = appClients.map((client, i) => buildAppClient(client, i)).join('\n\n');

  const smsRole =
    mfa.enabled && mfa.methods.includes('sms')
      ? `
  CognitoSMSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cognito-idp.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CognitoSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sns:publish
                Resource: '*'`
      : '';

  const outputs = appClients
    .map((client, i) => {
      const logicalId = `AppClient${sanitize(client.name || `Client${i + 1}`)}`;
      return `
  ${logicalId}Id:
    Value: !Ref ${logicalId}
    Export:
      Name: !Sub '\${AWS::StackName}-${logicalId}Id'`;
    })
    .join('');

  return `AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cognito User Pool - ${poolName || 'MyUserPool'}
  Provider: ${provider.toUpperCase()} | Region: ${region}
  Generated by auth-cli

Metadata:
  AuthCli:
    Provider: ${provider}
    Region: ${region}

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${poolName || 'MyUserPool'}-\${Environment}'
      DeletionProtection: ${deletionProtection ? 'ACTIVE' : 'INACTIVE'}
      UsernameConfiguration:
        CaseSensitive: false${
          aliasAttrs.length
            ? `
      AliasAttributes:${aliasAttrs.map((a) => `\n        - ${a}`).join('')}`
            : ''
        }${
          autoVerifiedAttrs.length
            ? `
      AutoVerifiedAttributes:${autoVerifiedAttrs.map((a) => `\n        - ${a}`).join('')}`
            : ''
        }
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: ${selfSignup ? 'false' : 'true'}
      Policies:
        PasswordPolicy:
          MinimumLength: ${passwordPolicy.minLength}
          RequireUppercase: ${passwordPolicy.requireUppercase}
          RequireLowercase: ${passwordPolicy.requireLowercase}
          RequireNumbers: ${passwordPolicy.requireNumbers}
          RequireSymbols: ${passwordPolicy.requireSymbols}
          TemporaryPasswordValidityDays: ${passwordPolicy.tempPasswordDays}
      MfaConfiguration: '${mfaConfig}'${enabledMfas}${smsConfig}
      AccountRecoverySetting:
        RecoveryMechanisms:${recoveryMechanisms
          .map((m) => `\n          - Name: ${m.name}\n            Priority: ${m.priority}`)
          .join('')}${
          autoVerifiedAttrs.length
            ? `
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:${autoVerifiedAttrs
          .map((a) => `\n          - ${a}`)
          .join('')}`
            : ''
        }${
          lambdaConfig
            ? `
      LambdaConfig:${lambdaConfig}`
            : ''
        }
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: false
          Mutable: true${
            customAttributes.length
              ? `\n${customAttributes.map(buildCustomAttributeSchema).join('\n')}`
              : ''
          }
      UserPoolTags:
        Environment: !Ref Environment
        ManagedBy: auth-cli
${appClientResources}
${smsRole}

Outputs:
  UserPoolId:
    Value: !Ref UserPool
    Export:
      Name: !Sub '\${AWS::StackName}-UserPoolId'
  UserPoolArn:
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub '\${AWS::StackName}-UserPoolArn'${outputs}
`;
}

function buildLambdaConfig(triggers: LambdaTriggers): string {
  const lines = Object.entries(triggers)
    .filter(([, arn]) => arn && arn.trim())
    .map(
      ([key, arn]) =>
        `\n        ${LAMBDA_TRIGGER_CFN_KEYS[key as keyof LambdaTriggers]}: '${arn.trim()}'`,
    );

  return lines.join('');
}

function buildAppClient(client: AppClient, index: number): string {
  const logicalId = `AppClient${sanitize(client.name || `Client${index + 1}`)}`;
  const flows = client.authFlows || [];
  const callbackUrls = client.callbackUrls?.filter(Boolean) ?? [];
  const logoutUrls = client.logoutUrls?.filter(Boolean) ?? [];

  return `  ${logicalId}:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: '${client.name || `client-${index + 1}`}'
      UserPoolId: !Ref UserPool
      GenerateSecret: ${client.generateSecret || false}
      ExplicitAuthFlows:${
        flows.length
          ? flows.map((f) => `\n        - ${f}`).join('')
          : '\n        - ALLOW_REFRESH_TOKEN_AUTH'
      }
      AccessTokenValidity: ${client.accessTokenValidity || 60}
      IdTokenValidity: ${client.idTokenValidity || 60}
      RefreshTokenValidity: ${client.refreshTokenValidity || 30}
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: true${
        callbackUrls.length
          ? `
      CallbackURLs:${callbackUrls.map((u) => `\n        - '${u}'`).join('')}`
          : ''
      }${
        logoutUrls.length
          ? `
      LogoutURLs:${logoutUrls.map((u) => `\n        - '${u}'`).join('')}`
          : ''
      }${
        callbackUrls.length || logoutUrls.length
          ? `
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      SupportedIdentityProviders:
        - COGNITO`
          : ''
      }`;
}

function buildCustomAttributeSchema(attr: CustomAttribute): string {
  const constraints =
    attr.type === 'String'
      ? `\n          StringAttributeConstraints:\n            MinLength: '${attr.minLength ?? 0}'\n            MaxLength: '${attr.maxLength ?? 256}'`
      : attr.type === 'Number'
        ? `\n          NumberAttributeConstraints:\n            MinValue: '${attr.minValue ?? 0}'\n            MaxValue: '${attr.maxValue ?? 9999999}'`
        : '';

  return `        - Name: ${attr.name}
          AttributeDataType: ${attr.type}
          DeveloperOnlyAttribute: false
          Required: ${attr.required}
          Mutable: ${attr.mutable}${constraints}`;
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, '');
}
